env: pybullet.TableEnv
env_kwargs:
  name: pull
  gui: true

  primitives:
    - pick
    - place
    - pull

  tasks:
    - action_skeleton:
        - pull(table_box_1, hook)
      initial_state:
        - handlegrasp(hook)
        - free(table_box_1)
        - aligned(rack)
        - poslimit(rack)
        - beyondworkspace(table_box_1)
        - nonblocking(table_box_1, rack)
        - on(rack, table)
        - on(table_box_1, table)
        - on(table_box_2, table)
        - on(rack_box_1, rack)
        - on(rack_box_2, rack)
        - inhand(hook)

  robot_config: configs/pybullet/envs/robots/franka_panda_sim.yaml

  object_groups:
    - name: boxes
      objects:
        - object_type: Box
          object_kwargs:
            size: [0.05, 0.05, 0.1]
            color: [1.0, 0.0, 0.0, 1.0]
        - object_type: Box
          object_kwargs:
            size: [0.1, 0.05, 0.1]
            color: [0.0, 0.0, 1.0, 1.0]
        - object_type: Null
        - object_type: Null
        - object_type: Null
        - object_type: Null

  objects:
    - object_type: Urdf
      object_kwargs:
        name: table
        path: configs/pybullet/envs/assets/iprl_table.urdf
        is_static: true
    - object_type: Variant
      object_kwargs:
        name: rack
        variants:
          - object_type: Rack
            object_kwargs:
              size: [0.22, 0.32, 0.16]
              color: [0.4, 0.2, 0.0, 1.0]
          - object_type: Null
    - object_type: Hook
      object_kwargs:
        name: hook
        head_length: 0.2
        handle_length: 0.38
        handle_y: -1.0
        color: [0.6, 0.6, 0.6, 1.0]
    - object_type: Variant
      object_kwargs:
        name: table_box_1
        group: boxes
    - object_type: Variant
      object_kwargs:
        name: table_box_2
        group: boxes
    - object_type: Variant
      object_kwargs:
        name: rack_box_1
        group: boxes
    - object_type: Variant
      object_kwargs:
        name: rack_box_2
        group: boxes
