env: pybullet.TableEnv
env_kwargs:
  name: pick
  gui: true

  primitives:
    - pick

  tasks:
    - action_skeleton:
        - pick(a, table)
      initial_state:
        - on(a, table)
        - istippable(a)
        - on(b, table)
        - istippable(b)
        - on(c, table)
    # - action_skeleton:
    #     - pick(box, table)
    #   initial_state:
    #     - on(box, table)
    #     - istippable(box)
    #     - on(hook, table)
    #     - istippable(hook)
    # - action_skeleton:
    #     - pick(hook, table)
    #   initial_state:
    #     - on(box, table)
    #     - istippable(box)
    #     - on(hook, table)
    #     - istippable(hook)

  robot_config: configs/pybullet/envs/robots/franka_panda_sim.yaml
  # robot_config: configs/pybullet/envs/robots/franka_panda_real.yaml
  # object_tracker_config: configs/pybullet/envs/perception/object_tracker.yaml

  object_groups:
    - name: movable
      objects:
      - object_type: Box
        object_kwargs:
          size: [0.05, 0.05, 0.1]
          color: [1.0, 0.0, 0.0, 1.0]
      - object_type: Box
        object_kwargs:
          size: [0.05, 0.1, 0.1]
          color: [0.0, 0.0, 1.0, 1.0]
      - object_type: Hook
        object_kwargs:
          head_length: 0.2
          handle_length: 0.38
          handle_y: -1.0
          color: [0.4, 0.2, 0.0, 1.0]
      - object_type: Null
      - object_type: Null

  objects:
    - object_type: Urdf
      object_kwargs:
        name: table
        path: configs/pybullet/envs/assets/iprl_table.urdf
        is_static: true
    - object_type: Variant
      object_kwargs:
        name: a
        group: movable
    - object_type: Variant
      object_kwargs:
        name: b
        group: movable
    - object_type: Variant
      object_kwargs:
        name: c
        group: movable
    # - object_type: Box
    #   object_kwargs:
    #     name: box
    #     size: [0.05, 0.05, 0.1]
    #     color: [1.0, 0.0, 0.0, 1.0]
    # - object_type: Hook
    #   object_kwargs:
    #     name: hook
    #     head_length: 0.2
    #     handle_length: 0.38
    #     handle_y: -1.0
    #     color: [0.4, 0.2, 0.0, 1.0]
