env: pybullet.TableEnv
env_kwargs:
  name: pull
  gui: true

  primitives:
    - pull

  action_skeleton:
    - pull(a, hook)

  initial_state:
    - on(a, table)
    - beyondworkspace(a)
    - inhand(hook)
    # - on(b, table)
    # - istippable(b)

  robot_config: configs/pybullet/envs/robots/franka_panda_sim.yaml

  objects:
    - object_type: Urdf
      object_kwargs:
        name: table
        path: configs/pybullet/envs/assets/iprl_table.urdf
        is_static: true
    - object_type: Box
      object_kwargs:
        name: a
        size: [0.05, 0.05, 0.1]
        color: [1.0, 0.0, 0.0, 1.0]
    - object_type: Hook
      object_kwargs:
        name: hook
        head_length: 0.2
        handle_length: 0.38
        handle_y: -1.0
        color: [0.4, 0.2, 0.0, 1.0]
    # - object_type: Box
    #   object_kwargs:
    #     name: b
    #     size: [0.05, 0.05, 0.1]
    #     color: [1.0, 0.0, 0.0, 1.0]
