env: pybullet.TableEnv
env_kwargs:
  name: workspace
  gui: true

  primitives:
    - pick
    - place
    - pull

  tasks:
    - action_skeleton:
        - pick(hook, table)
        - pull(a, hook)
        - place(hook, table)
        - pick(a, table)
      initial_state:
        - on(hook, table)
        - on(a, table)
        - beyondworkspace(a)
        - inworkspace(hook)

  robot_config: configs/pybullet/envs/robots/franka_panda_sim.yaml

  objects:
    - object_type: Urdf
      object_kwargs:
        name: table
        path: configs/pybullet/envs/assets/iprl_table.urdf
        is_static: true
    - object_type: Box
      object_kwargs:
        name: a
        size: [0.05, 0.05, 0.1]
        color: [1.0, 0.0, 0.0, 1.0]
    - object_type: Hook
      object_kwargs:
        name: hook
        head_length: 0.2
        handle_length: 0.38
        handle_y: -1.0
        color: [0.4, 0.2, 0.0, 1.0]
