planner: ShootingPlanner
planner_kwargs:
  num_samples: 128

agent_configs:
  - agent: OracleAgent
    agent_kwargs:
      agent_config:
        agent: GaussianAgent
        agent_kwargs:
          agent_config: "{AGENT_CONFIG}"
          std: 0.5
  - agent: OracleAgent
    agent_kwargs:
      agent_config: "{AGENT_CONFIG}"

dynamics_config: "{DYNAMICS_CONFIG}"
