planner: CEMPlanner
planner_kwargs:
  num_samples: 16
  num_iterations: 8

agent_configs:
  - agent: RandomAgent
    agent_kwargs:
      agent_config: "{AGENT_CONFIG}"
  - "{AGENT_CONFIG}"

dynamics_config:
  dynamics: OracleDynamics
