env: pybullet.TableEnv
env_kwargs:
  name: lifted_1
  gui: false

  primitives:
    - pick
    - place
    - pull
    - push

  tasks:
    - instruction: How would you put a prime colored box on the rack?
      action_skeleton:
        - pick(hook)
        - pull(blue_box, hook)
        - place(hook, table)
        - pick(blue_box)
        - place(blue_box, rack)
      initial_state:
        - free(hook)
        - free(blue_box)
        - free(cyan_box)
        - aligned(rack)
        - poslimit(rack)
        - inworkspace(rack)
        - inworkspace(hook)
        - inworkspace(cyan_box)
        - beyondworkspace(blue_box)
        - nonblocking(blue_box, rack)
        - nonblocking(blue_box, cyan_box)
        - on(rack, table)
        - on(hook, table)
        - on(blue_box, table)
        - on(cyan_box, table)
      goal_propositions:
        - on(blue_box, rack)
      supported_predicates:
        - under(a, b)
        - on(a, b)
        - inhand(a)
        
  robot_config: configs/pybullet/envs/robots/franka_panda_sim.yaml

  objects:
    - object_type: Urdf
      object_kwargs:
        name: table
        path: configs/pybullet/envs/assets/iprl_table.urdf
        is_static: true
    - object_type: Rack
      object_kwargs:
        name: rack
        size: [0.22, 0.32, 0.16]
        color: [0.4, 0.2, 0.0, 1.0]
    - object_type: Hook
      object_kwargs:
        name: hook
        head_length: 0.2
        handle_length: 0.38
        handle_y: -1.0
        color: [0.6, 0.6, 0.6, 1.0]
    - configs/pybullet/envs/assets/salt.yaml
    - configs/pybullet/envs/assets/icecream.yaml
