env: pybullet.TableEnv
env_kwargs:
  name: hook_reach_9
  gui: true

  primitives:
    - pick
    - place
    - pull

  tasks:
    - action_skeleton:
        - pick(hook, rack)
        - pull(red_box, hook)
        - place(hook, rack)
        - pick(red_box, table)
      initial_state:
        - inworkspace(rack)
        - inworkspace(hook)
        - on(rack, table)
        - on(hook, rack)
        - beyondworkspace(red_box)
        - on(red_box, table)
        
  robot_config: configs/pybullet/envs/robots/franka_panda_sim.yaml

  objects:
    - object_type: Urdf
      object_kwargs:
        name: table
        path: configs/pybullet/envs/assets/iprl_table.urdf
        is_static: true
    - object_type: Rack
      object_kwargs:
        name: rack
        size: [0.22, 0.32, 0.16]
        color: [0.4, 0.2, 0.0, 1.0]
    - object_type: Hook
      object_kwargs:
        name: hook
        head_length: 0.2
        handle_length: 0.38
        handle_y: -1.0
        color: [0.6, 0.6, 0.6, 1.0]
    - object_type: Box
      object_kwargs:
        name: red_box
        size: [0.05, 0.05, 0.07]
        color: [1.0, 0.0, 0.0, 1.0]