trainer: UnifiedTrainer
trainer_kwargs:
  dynamics_trainer_config: configs/pybox2d/trainers/dynamics.yaml
  agent_trainer_configs:
    - configs/pybox2d/trainers/agent.yaml
    - configs/pybox2d/trainers/agent.yaml

  num_pretrain_steps: 1000
  num_train_steps: 200000
  num_eval_steps: 100
  eval_freq: 1000
  checkpoint_freq: 50000
  log_freq: 1000
  profile_freq: 100
