env: pybullet.TableEnv
env_kwargs:
  name: constrained_packing_1
  gui: true

  primitives:
    - pick
    - place
    - pull
    - push

  tasks:
    - action_skeleton:
        - pick(yellow_box, table)
        - place(yellow_box, rack)
        - pick(cyan_box, table)
        - place(cyan_box, rack)
        - pick(blue_box, table)
        - place(blue_box, rack)
      initial_state:
        - free(yellow_box)
        - free(cyan_box)
        - free(blue_box)
        - aligned(rack)
        - poslimit(rack)
        - inworkspace(rack)
        - inworkspace(yellow_box)
        - inworkspace(cyan_box)
        - inworkspace(blue_box)
        - on(rack, table)
        - on(yellow_box, table)
        - on(cyan_box, table)
        - on(blue_box, table)

  # robot_config: configs/pybullet/envs/robots/franka_panda_sim.yaml
  robot_config: configs/pybullet/envs/robots/franka_panda_real.yaml
  object_tracker_config: configs/pybullet/envs/perception/object_tracker.yaml

  objects:
    - object_type: Urdf
      object_kwargs:
        name: table
        path: configs/pybullet/envs/assets/iprl_table.urdf
        is_static: true
    - object_type: Rack
      object_kwargs:
        name: rack
        size: [0.22, 0.32, 0.16]
        color: [0.4, 0.2, 0.0, 1.0]
    - configs/pybullet/envs/assets/salt.yaml
    - configs/pybullet/envs/assets/yogurt.yaml
    - configs/pybullet/envs/assets/icecream.yaml
    # - object_type: Box
    #   object_kwargs:
    #     name: blue_box
    #     size: [0.08, 0.05, 0.07]
    #     color: [0.0, 0.0, 1.0, 1.0]
    # - object_type: Box
    #   object_kwargs:
    #     name: yellow_box
    #     size: [0.07, 0.06, 0.1]
    #     color: [1.0, 1.0, 0.0, 1.0]
    # - object_type: Box
    #   object_kwargs:
    #     name: cyan_box
    #     size: [0.06, 0.03, 0.06]
    #     color: [0.0, 1.0, 1.0, 1.0]
