planner: ShootingPlanner
planner_kwargs:
  num_samples: 100000

agent_configs:
  - agent: RandomAgent
    agent_kwargs:
      agent_config: "{AGENT_CONFIG}"
  - agent: RandomAgent
    agent_kwargs:
      agent_config: "{AGENT_CONFIG}"
  - agent: RandomAgent
    agent_kwargs:
      agent_config: "{AGENT_CONFIG}"
  - agent: RandomAgent
    agent_kwargs:
      agent_config: "{AGENT_CONFIG}"

dynamics_config: "{DYNAMICS_CONFIG}"
