env: pybullet.TableEnv
env_kwargs:
  name: hook_reach_2
  gui: true

  primitives:
    - pick
    - place
    - pull
    - push

  tasks:
    - action_skeleton:
        - pick(hook, table)
        - pull(red_box, hook)
        - place(hook, table)
        - pick(red_box, table)
      initial_state:
        - free(hook)
        - free(red_box)
        - free(cyan_box)
        - free(yellow_box)
        - inworkspace(hook)
        - beyondworkspace(red_box)
        - nonblocking(red_box, cyan_box)
        - nonblocking(red_box, yellow_box)
        - on(hook, table)
        - on(red_box, table)
        - on(cyan_box, table)
        - on(yellow_box, table)
          
  robot_config: configs/pybullet/envs/robots/franka_panda_sim.yaml

  objects:
    - object_type: Urdf
      object_kwargs:
        name: table
        path: configs/pybullet/envs/assets/iprl_table.urdf
        is_static: true
    - object_type: Hook
      object_kwargs:
        name: hook
        head_length: 0.2
        handle_length: 0.38
        handle_y: -1.0
        color: [0.6, 0.6, 0.6, 1.0]
    - configs/pybullet/envs/assets/yogurt.yaml
    - configs/pybullet/envs/assets/milk.yaml
    - configs/pybullet/envs/assets/icecream.yaml
    # - object_type: Box
    #   object_kwargs:
    #     name: yellow_box
    #     size: [0.07, 0.06, 0.1]
    #     color: [1.0, 1.0, 0.0, 1.0]
    # - object_type: Box
    #   object_kwargs:
    #     name: red_box
    #     size: [0.05, 0.05, 0.07]
    #     color: [1.0, 0.0, 0.0, 1.0]
    # - object_type: Box
    #   object_kwargs:
    #     name: cyan_box
    #     size: [0.06, 0.03, 0.06]
    #     color: [0.0, 1.0, 1.0, 1.0]
